name: living_network
description: A new Flutter module project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  living_network_repository:
#    path: /Users/pongstec/mfaf/living_network_repository/
    git:
      url: https://git.matador.ais.co.th/mfaf/mobileapp/mfaf_flutter/data/living_network_repository.git
      ref: develop

  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.2.4
  syncfusion_flutter_gauges: ^20.4.52
  shared_preferences: ^2.0.18
  realm: ^1.0.2
  carousel_slider: ^4.2.1
  solid_bottom_sheet: ^0.1.10
  provider: ^6.0.5
  url_launcher: ^6.1.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/piggy.gif
    - assets/loading_boost_mode.gif
    - assets/loading_game_mode.gif
    - assets/loading_eco_mode.gif
    - assets/pig.gif

  fonts:
  - family: DB Heavent
    fonts:
      - asset: assets/fonts/DB Heavent Bd Cond It v3.2.1.ttf
      - asset: assets/fonts/DB Heavent Bd Cond v3.2.1.ttf
      - asset: assets/fonts/DB Heavent Cond It v3.2.1.ttf
      - asset: assets/fonts/DB Heavent Cond v3.2.1.ttf
  
  module:
    androidX: true
    androidPackage: com.mfaf.livingnetwork.living_network
    iosBundleIdentifier: com.mfaf.livingnetwork.livingNetwork
