// ignore_for_file: unnecessary_this

class Autogenerated {
  String? msisdn;
  String? networkType;
  String? celled;
  String? paymentType;
  String? modelType;
  String? customerState;
  String? bssrrule;

  Autogenerated(
      {this.msisdn,
      this.networkType,
      this.celled,
      this.paymentType,
      this.modelType,
      this.customerState,
      this.bssrrule});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    msisdn = json['msisdn'];
    networkType = json['networkType'];
    celled = json['celled'];
    paymentType = json['paymentType'];
    modelType = json['modelType'];
    customerState = json['customerState'];
    bssrrule = json['bssrrule'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['msisdn'] = this.msisdn;
    data['networkType'] = this.networkType;
    data['celled'] = this.celled;
    data['paymentType'] = this.paymentType;
    data['modelType'] = this.modelType;
    data['customerState'] = this.customerState;
    data['bssrrule'] = this.bssrrule;
    return data;
  }
}
